"""add product catalogue domain tables

Revision ID: 3b53ecace330
Revises: 0168edeabafb
Create Date: 2026-07-31 13:57:21.510416
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3b53ecace330'
down_revision: str | None = '0168edeabafb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessories',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('for_products', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'roadmap')", name=op.f('ck_accessories_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessories'))
    )
    op.create_index(op.f('ix_accessories_category'), 'accessories', ['category'], unique=False)
    op.create_index(op.f('ix_accessories_sku'), 'accessories', ['sku'], unique=True)
    op.create_table('activity_log',
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("type IN ('create', 'update', 'delete')", name=op.f('ck_activity_log_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    op.create_index(op.f('ix_activity_log_at'), 'activity_log', ['at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('enquiries',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('org', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('interest', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new', 'replied', 'closed')", name=op.f('ck_enquiries_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enquiries'))
    )
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('series', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('form_factor', sa.String(length=80), nullable=False),
    sa.Column('has_models', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('applications', sa.JSON(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'roadmap')", name=op.f('ck_products_status_valid')),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name=op.f('fk_products_category_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_table('chassis_models',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('ru', sa.String(length=10), nullable=False),
    sa.Column('img', sa.String(length=300), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('family', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'roadmap')", name=op.f('ck_chassis_models_status_valid')),
    sa.ForeignKeyConstraint(['family'], ['products.id'], name=op.f('fk_chassis_models_family_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chassis_models'))
    )
    op.create_index(op.f('ix_chassis_models_family'), 'chassis_models', ['family'], unique=False)
    op.create_table('jupiter_models',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=80), nullable=False),
    sa.Column('rack_units', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'roadmap')", name=op.f('ck_jupiter_models_status_valid')),
    sa.ForeignKeyConstraint(['family'], ['products.id'], name=op.f('fk_jupiter_models_family_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jupiter_models'))
    )
    op.create_index(op.f('ix_jupiter_models_code'), 'jupiter_models', ['code'], unique=True)
    op.create_index(op.f('ix_jupiter_models_family'), 'jupiter_models', ['family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jupiter_models_family'), table_name='jupiter_models')
    op.drop_index(op.f('ix_jupiter_models_code'), table_name='jupiter_models')
    op.drop_table('jupiter_models')
    op.drop_index(op.f('ix_chassis_models_family'), table_name='chassis_models')
    op.drop_table('chassis_models')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_table('enquiries')
    op.drop_table('categories')
    op.drop_index(op.f('ix_activity_log_at'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_accessories_sku'), table_name='accessories')
    op.drop_index(op.f('ix_accessories_category'), table_name='accessories')
    op.drop_table('accessories')
    # ### end Alembic commands ###
